
const SEARCH_USERS_LOADING = 'SEARCH_USERS_LOADING'
const SEARCH_USERS_DATA_SUCCESS = 'SEARCH_USERS_DATA_SUCCESS'
const SEARCH_USERS_DATA_ERROR = 'SEARCH_USERS_DATA_ERROR'
const SEARCH_REPO_LOADING = 'SEARCH_REPO_LOADING'
const SEARCH_REPO_DATA_SUCCESS = 'SEARCH_REPO_DATA_SUCCESS'
const SEARCH_REPO_DATA_ERROR = 'SEARCH_REPO_DATA_ERROR'

export {
  SEARCH_USERS_LOADING,
  SEARCH_USERS_DATA_SUCCESS,
  SEARCH_USERS_DATA_ERROR,
  SEARCH_REPO_LOADING,
  SEARCH_REPO_DATA_SUCCESS,
  SEARCH_REPO_DATA_ERROR
}